version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/simpleskiresort/
permissions:
  - object: /home/ec2-user/simpleskiresort/
    pattern: "*.sh"
    owner: ec2-user
    mode: 777
    type:
      - file
hooks:
  ApplicationStart:
   - location: applicationstart.sh
     timeout: 300
     runas: root