version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/simpleskiresort/
permissions:
  - object: /home/ec2-user/simpleskiresort/
    pattern: "*.sh"
    mode: 777
    type:
      - file
hooks:
  ApplicationStart:
   - location: /home/ec2-user/simpleskiresort/as.sh
     timeout: 300
     runas: root