version: "3.9"
services: 
    skiresort-container:
         restart: always
         build: .
         ports: 
             - "9999:9999"
         environment: 
             PG_HOST: postgres
             PG_PORT: 5432
             PG_USER: postgres
             PG_PASSWORD: testpwd
             PG_DBNAME: postgres